In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [3]:
data = pd.read_csv('insurance.csv')

In [4]:
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

a. Shape of the data

In [5]:
data.shape

(1338, 7)

b. Data Type of each attribute

In [6]:
data.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

c. Checking the presence of missing values

In [7]:
data.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

d. 5 point summary of numerical attributes

In [18]:
NewData = data.loc[: , ['age', 'bmi', 'children', 'charges']]

quartiles = np.percentile(NewData, [25, 50, 75])

data_min, data_max = NewData.min(), NewData.max()

print("Min:\n", data_min)
print("...."*10)
print("Q1:\n", quartiles)
print("Median:\n", quartiles)
print("Q3:\n", quartiles)
print("...."*10)
print("Max:\n", data_max)

Min:
 age           18.0000
bmi           15.9600
children       0.0000
charges     1121.8739
dtype: float64
........................................
Q1:
 [ 13.22      32.47     328.468475]
Median:
 [ 13.22      32.47     328.468475]
Q3:
 [ 13.22      32.47     328.468475]
........................................
Max:
 age            64.00000
bmi            53.13000
children        5.00000
charges     63770.42801
dtype: float64


In [19]:
data.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010